//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: chessData.h
//  Source: ../idl/chessData.idl
//  Generated: Thu Mar 30 23:13:52 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _CHESSDATA_H_
#define _CHESSDATA_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"


namespace chessData
{
   struct Msg;

   struct Msg
   {
         DDS::Long userID;
         DDS::String_mgr message;
   };

   typedef DDS_DCPSStruct_var < Msg> Msg_var;
   typedef DDS_DCPSStruct_out < Msg> Msg_out;
}




#endif 
