//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: chessData.cpp
//  Source: ../idl/chessData.idl
//  Generated: Thu Mar 30 23:13:52 2017
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************

#include "chessData.h"




